# Generated by Django 5.0.7 on 2024-07-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('soup', models.CharField(blank=True, max_length=900, null=True)),
                ('main_course_opt1', models.CharField(blank=True, max_length=900, null=True)),
                ('main_course_opt2', models.CharField(blank=True, max_length=900, null=True)),
                ('side', models.CharField(blank=True, max_length=900, null=True)),
            ],
        ),
    ]
