# Generated by Django 5.0.7 on 2024-07-31 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='main_course_opt1',
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='main_course_opt2',
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='side',
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='main_course1_opt1',
            field=models.CharField(default='default value', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='main_course1_opt2',
            field=models.CharField(default='default value', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='main_course2',
            field=models.CharField(default='default value', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='sides',
            field=models.CharField(default='default value', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='soup',
            field=models.CharField(default='default value', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
